jkcfg/jk

- .travis.yml
Because we do everything in containers, we need very little things from the
travis image.
> build: Use the minimal language in travis

- main.go
We definitely want to know why when failing to load a module, make sure to
print the cause!
> jk: Print exception when failing to load a module

- run.go
The resolver will find imports that are given relative to the module in question. But this has to be kicked off by giving the top-level resolver the path to the script to be run.
> Make resolver relative to supplied script

- Makefile
If jk is the first binary to be installed there, the directoy may not exist.
Create it first!
> build: Ensure `go env GOPATH`/bin is a directory before installing

- .travis.yml
This reverts commit 14bb603af3bfc6ff9488124ceaa8d7accbbe1025.
Now that we have flact in the prebuilt repo, we can compile on macOS once
again.
> Revert "ci: Allow travis to fail on macOS until we have flatc there"

- run.go
- std/package.json
- std/shim/.gitignore
- std/shim/.npmignore
- std/shim/package-lock.json
- std/shim/package.json
- std/shim/std.ts
- std/shim/tsconfig.json
- tests/README.md
- tests/e2e_test.go
- tests/success.json
- tests/test-std-ts.js.cmd
- tests/test-std-ts.js.expected
- tests/test-std-ts/.gitignore
- tests/test-std-ts/package.json
- tests/test-std-ts/test.ts
- tests/test-std-ts/tsconfig.json
Wrote a small std shim in typescript so we can have types for the standard library. The goal is to distribute it with npm so people can put it in their devDependencies and be able to write typescript code calling std functions.
A test is included, trying to cover most of the std interface.
The shim isn't currently doing anything, it's just there for types. In the future I guess we could have something that could run on node, maybe useful for testing.
> A std shim in typescript

- std/std_write.js
We don't want to expose this field, it's an internal detail.
Fixes: #49
> std: Remove Format.Auto from the public object

- std/shim/std.ts
- std/std.js
- std/std_print.js
- tests/test-std-ts.js.expected
- tests/test-std-ts/test.ts
Log is designed to print out a JSON object and so isn't so convenient to print
raw strings. std.print() helps there.
> std: Add a print function

- go.mod
- pkg/std/param.go
- pkg/std/params.go
- pkg/std/params_test.go
- pkg/std/std.go
- run.go
- std/__std.fbs
- std/__std_Param.fbs
- std/std.js
- std/std_param.js
- tests/README.md
- tests/e2e_test.go
- tests/test-params-from-file.js
- tests/test-params-from-file.js.cmd
- tests/test-params-from-file.js.expected
- tests/test-params-from-file.json
- tests/test-params-merge-object.js
- tests/test-params-merge-object.js.cmd
- tests/test-params-merge-object.js.expected
- tests/test-params-merge-object.json
- tests/test-params-override.js
- tests/test-params-override.js.cmd
- tests/test-params-override.js.expected
- tests/test-params-override.json
- tests/test-params.js
- tests/test-params.js.cmd
- tests/test-params.js.expected
This PR introduces script input parameters through a new std API: `std.param`. To define a new parameter one writes:
```
const version = std.param.String("version", "0.1.0");
std.print(version);
```
The user can provide a new value from the command line:
```
$ jk run --ps version=1.0.0 script.js
```
Or from a json file with the `-p` option.
Input parameters are in fact organised as a big JSON object, and can be addressed by their path, eg. `"global.version` is the parameter:
```
{
...
"global": {
...
"version": "xxx",
...
},
...
}
```
Fixes: #18
> Input parameters

- std/.prettierrc
- std/package-lock.json
- std/package.json
Using terser has the unfortunate side-effect to produce a one-line std.js which
makes exceptions that happen in std print a gigantic mangled line.
We now use terser for its dead-code elimination pass and use prettier to
reformat the result.
Exceptions now look like:
```
$ cat test-std-exception.js
import std from 'std';
std.read(undefined);
$ jk run test-std-exception.js
std:1031
while (i < s.length) {
^
TypeError: Cannot read property 'length' of undefined
at flatbuffers.Builder.createString (std:1031:18)
at Object.read (std:1393:29)
at test-std-exception.js:3:5
```
> std: User rollup + terser + prettier to produce std.js

- go.mod
- go.sum
Details are at:  https://github.com/ry/v8worker2/pull/29
Fixes: #71 
Fixes: #91
> Correctly handle buffer ownership in the go -> js path

- pkg/resolve/file_importer.go
- pkg/resolve/npm.go
- pkg/resolve/npm_test.go
- pkg/resolve/resolver.go
- pkg/resolve/static_importer.go
- pkg/resolve/types.go
- tests/node_modules/testcase/index.js
- tests/node_modules/testcase/indirect.js
- tests/node_modules/testcase/package.json
- tests/node_modules/testcase/subdir/package.json
- tests/node_modules/testcase/subdir/test4.js
- tests/node_modules/testcase/submodule.js
- tests/node_modules/testcase/test3.js
- tests/test-npm-imports.expected/test1.json
- tests/test-npm-imports.expected/test2.json
- tests/test-npm-imports.expected/test3.json
- tests/test-npm-imports.expected/test4.json
- tests/test-npm-imports.js
Prior to npm module resolution, the specifier for a module and the
file path had a direct relationship, and it was a reasonable
approximation to make base/specifier the new base for recursive
imports.
However, npm modules can be resolved to paths that don't correspond
closely with the specifier; so, explicitly return the filesystem path
from `Import` and use that to resolve recursive imports.
(Another way to do this would be to take the top path from the candidates list, and assume the contract that it must be the successful path (if bytes is not empty).)
> Use resolved path when resolving relative imports

- run.go
- std/std_deferred.js
V8Worker2 will look for a global called `onerror`; so load one before
starting.
Also: without intervention, errors that come from the "deferred"
system (when the runtime does something for you and returns the result
later) will have a helpful error message (because we pass it back to
JS), but a meaningless stack trace (because it starts where control
re-enters JS, i.e., at `recv`). To make it a bit more useful, capture
the stack trace when entering code that asks for a deferred value, and
transplant it to any eventual error.
> Supply a fallback promise rejection handler

- Makefile
Unfortunately, the tags created with the UI aren't annotated (ie. created with
-a), so git descibe wasn't taking them into account, showing the version still
as a 0.2.0-...
> build: Make git describe consider lightweight tags too

- pkg/std/write.go
- std/shim/std.ts
- std/std.js
- std/std_print.js
- tests/test-import-script-not-in-cwd.js.expected
- tests/test-log.js.expected
- tests/test-std-ts.js.expected
- tests/test-std-ts/test.ts
- tests/test-write.expected/test-write-json-string.json
- tests/test-write.js
The current behaviour of `log` printing JSON values isn't ideal when printing astring. We have:
std.log('foo') => "foo"
We special case strings so we don't end up with the double quotes. It's really confusing and hard to work around.
A last detail: when asked to write JSON though, we make sure to still print strings as JSON values!
Fixes: #96
> consolidate print and log

- pkg/resolve/npm.go
- pkg/std/read.go
- pkg/std/std.go
- run.go
- tests/input.json
- tests/input/input.json
- tests/input/test.js
- tests/node_modules/testcase/node_modules/vendored/index.js
- tests/node_modules/testcase/vendor.js
- tests/test-input-directory-elsewhere.js.cmd
- tests/test-input-directory-elsewhere.js.expected
- tests/test-input-directory-scriptdir.js.cmd
- tests/test-input-directory-scriptdir.js.expected
- tests/test-npm-imports.expected/test5.json
- tests/test-npm-imports.js
- tests/test-std-ts.js.cmd
This adds an option for the runtime to tell it
the base directory for reads. The idea is that relative paths will be
interpreted with respect to the base path.
This opens the way to providing a directory _other_ than the current
working directory -- e.g., that of the script being run.
If we are being strictly hermetic, absolute paths should be
disallowed. For the minute, I've just restricted them to paths that
happen to be under the base path.
The two flags to control this are
* --directory,-C meaning use the given directory as the base; and,
* --use-script-dir meaning use the directory the script is in as the base.
It occurs to me that another formulation is to have just `--directory,-C` and otherwise assume the script dir is the base dir. In that case, if you want to run a script that …
> Introduce exec option for root read directory

- jk.go
With RunE functions, cobra prints out the err and usage string itself before
handing over the error to us. We want to be in full control of what is
diplayed, though and currently we print the error twice:
```
$ jk run -p fo
Error: invalid argument "fo" for "-p, --parameter" flag: input parameters are of the form name=value
Usage:
jk run [flags]
Flags:
-h, --help                      help for run
-i, --input-directory string    where to find files read in the script; if not set, the directory containing the     script is used
-o, --output-directory string   where to output generated files
-p, --parameter name=value      boolean input parameter
-f, --parameters filename       load parameters from a JSON file
-v, --verbose                   verbose output
invalid argument "fo" for "-p, …
```
> jk: Silence errors and usage coming from cobra

- std/std_param.js
- tests/test-params-issue-122.js
- tests/test-params-issue-122.js.cmd
- tests/test-params-issue-122.js.expected
We had a bug for Object parameters specifically. For objects, we deep merge the
object default value with param sub-subtree that the user already provided and
so we need to send the object default value to the go side.
We were serializing the object default value as a JSON string for that but
without checking the user did specify a default object.
Fixes: #122
> param: Fix NPE when not specifying a default Object value

- go.mod
- pkg/std/read.go
- pkg/std/std.go
- pkg/std/write.go
- std/__std_Format.fbs
- std/__std_Read.fbs
- std/std_read.js
- tests/test-jsonstream.js
- tests/test-jsonstream.js.expected
- tests/test-yamlstream.js
- tests/test-yamlstream.js.expected
Adds the formats `YAMLStream` and `JSONStream`, and supports reading and writing them.
Addresses #93.
> Stream formats

- go.mod
- go.sum
- pkg/resolve/resolver.go
- pkg/resolve/types.go
- run.go
Adapts the jk runtime to the slightly changed module resolution in our (jkcfg) v8worker2, after https://github.com/jkcfg/v8worker2/pull/2.
> Use canonical module specifiers

- tests/test-module-resource.js
The termination of promises is non deterministic, in particular it means we
can't rely on std.log for resource1 to be called before std.log for resource2.
Instead, let's wait for all promises to be resolved and than cycle though their
values to log them to stdout.
> tests: Make logging the resources deterministic

- pkg/std/params.go
- pkg/std/params_test.go
- std/std_param.js
- tests/test-params-all.js
- tests/test-params-all.js.cmd
- tests/test-params-all.js.expected
> params: Add a all() function that returns all defined parameters

- pkg/std/fs.go
- pkg/std/read.go
- pkg/std/readbase.go
- pkg/std/resource.go
- pkg/std/std.go
- std/__std_FileSystem.fbs
- std/std_fs.js
- tests/test-module-resource.js
- tests/test-module-resource.js.expected
- tests/test-module-resource/dir/info
- tests/test-module-resource/fs.js
- tests/test-module-resource/resource.js
- tests/test-module-resource/submodule/resource.js
```
import { read, dir, info } from '@jkcfg/std/resource';
```
This tidies up the implementation of `dir` and `info` a bit as well:
- they now obey the input directory constraint
- names and paths in the output are more consistent
> Provide module-relative fs.dir and fs.info as well

- completion.go
- run.go
This PR adds autocompletion support for `bash` and `zsh`.
* Subcommand completion for both shells
* Filename completion for `jk run -f` in bash (`yaml`, `yml`, `json`). Cobra does not seem to support this in `zsh` at the moment.
* `bash`: `source  <(jk completion)`
* `zsh`: `jk completion zsh > _jk`, then move `_jk` into `$fpath` and run `compinit`.
Closes #113
> feat(cli): autocomplete

- README.md
This PR adds some basic contribution guide:
- Open issues before filing PR's
- How to setup a local working environment for building `jk`. I assume [jkcfg/prebuilt](https://github.com/jkcfg/prebuilt) is the preferred way of obtaining v8 and `flatc`? This setup guide worked for me locally on `linux/amd64` and `darwin/amd64`. 
I could not find any guide on this, so I put one where would search first. I hope this is not a duplicate ;)
Fixes: #45
> doc(README): Contribution guide

- .travis.yml
- README.md
- build/Dockerfile
- go.sum
We've had a report from @sh0rez that the go.sum we generate is not compatible with older versions of go. Bump the go version we use to 1.12.1
```
verifying github.com/google/flatbuffers@v1.10.0: checksum mismatch
downloaded: h1:wHCM5N1xsJ3VwePcIpVqnmjAqRXlR44gv4hpGi+/LIw=
go.sum:     h1:oRiOciRvbejW4wxTr/DVVAczyQaxsEONq6NyxhDf3bY=
```
- https://github.com/golang/go/issues/27093
- https://github.com/golang/go/issues/27925
- https://github.com/golang/go/issues/29278
> Bump the go version to 1.12.1

- pkg/resolve/npm.go
- pkg/resolve/npm_test.go
- pkg/resolve/testfiles/node_modules/modfoo/lib/bar.js
- pkg/resolve/testfiles/node_modules/modfoo/lib/bar/notindex.js
Briefly: if you have
```
node_modules/
foo/
bar.js
bar/
```
then import `foo/bar` will fail, because the resolver prefers the directory over the file, and can't backtrack once it discovers there's no index in the dir.
> Resolve files within packages correctly

- run.go
This adds examples of run invocation in the helper
bytes.Buffer is used because of using a const string on multiline returns bad indentations.
Fixes #115
> Run command help

- pkg/record/recorder.go
- pkg/resolve/resolver.go
- pkg/std/read.go
- pkg/std/readbase.go
- pkg/std/std.go
- run.go
- tests/README.md
- tests/e2e_test.go
- tests/test-run-dependencies.js
- tests/test-run-dependencies.js.cmd
- tests/test-run-dependencies.js.expected
- tests/test-run-dependencies/failure.js
- tests/test-run-dependencies/params.json
- tests/test-run-dependencies/svc-myapp.yaml
It can be useful for external programs to know the list of files a script
depends on. For instance, a program can watch that list of files and run jk
when one of them changes as it's possible running the script will produce a
different output.
We current emit only file dependencies:
- import-file: a file imported through an import statement
- parameter-file: a file with script input parameters specified with `-f`
- read-file: a file read by std lthe output has changed as well.ib
```console
$ jk run -f params.json -d ./read-simple.js 
[
{
"kind": "import-file",
"path": "/home/damien/go/src/github.com/jkcfg/jk/read-simple.js",
"specifier": "./read-simple.js"
},
{
"kind": "parameter-file",
"path": "/home/damien/go/src/github.com/jkcfg/jk/params.json"
},
{
"kind": "import-file",
"path": …
```
> run: Add an option to emit the list of a script dependencies

- go.mod
- go.sum
- params_option.go
- run.go
- vm.go
This PR refactors run into a `vm` object that can be reused to implement the generate command. I thought better submit this quickly than let it bitrot locally.
> Prep refactoring work for generate

- vm.go
This was from a time where each type had its own option name.
> vm: Fix help text of the -p option

- std/generate.js
- tests/generate-function.js
- tests/test-generate-function.expected/object.yaml
- tests/test-generate-function.js.cmd
The desire for the default export being a function has emerged from a comment
in:
https://github.com/jkcfg/jk/issues/125#issuecomment-491935449
That makes sense and is fortunately easy to add!
> generate: Support default export being a function

- std/package-lock.json
- tests/test-std-ts/package.json
Github believe we are the std package because the lock files still mentions
'std'. This means github things we are used by 3,059 packages. That's nice but
far from the truth.
> build: Don't tell github we're the std package

- examples/README.md
- examples/kubernetes/micro-service/kubernetes.js
We have defined a maintainer on the micro-service object, might as well wire it up to the resulting Kubernetes objects.
> Wire through the maintainer as a label on Kubernetes objects

- examples/kubernetes/micro-service/kubernetes.js
Oops, the TypeScript validation did catch something good! we didn't specify a selector in an `apps/v1` Deployment!
> examples: Add a selector to Kubernetes Deployments

- examples/kubernetes/micro-service/dashboard.js
This particular panel is the average of all routes, not a per-route latency
graph.
> examples: Fix the latency graph legend

- std/log.ts
- std/write.ts
- tests/test-log.js
- tests/test-log.js.expected
Instead of having log(undefined) throw a weird looking exception, we should
just print 'undefined'!
I've also changed write() to throw a human readable error when attempting to
write an undefined value. I don't think we want to silently ignore this, might
as well tell the user something is odd.
Fixes: 221
> std: Fix logging undefined values

- std/merge.js
There were some incorrect claims in the comments, no doubt left over from when I ported them over from @jkcfg/mixins.
> Remove inaccuracies from merge and patch comments

- .travis.yml
- Makefile
Docker images such as `busybox` lack the runtime libraries that are required by the current build of jk. This PR is to mitigate that problem by linking jk statically. There is no significant binary size impact.
I've tested the Linux amd64 build. I haven't tested the Darwin one.
> Makefile: make the build static to ease running in lean docker containers

- docs/deprecations.md
- std/.eslintrc
- std/merge.js
- std/merge.test.js
We've discussed with @squaremo how we could improve the current state of `std/merge`. `mergeFull` is the result of this.
We can now merge objects and specify for each key a merge strategy, allowing us to implement complex merges and the mechanism to implement Kubernetes strategic merging.
The API doc embed with `mergeFull`, `deep` and `deepWithKey` is somewhat extensive and has details and examples.
**Notes/questions**:
- I'd like to replace both `merge` and `patch` by `mergeFull` in `0.3.0` (renaming it `merge`).
- Should the various strategies live in a separate module?
- Merge strategies are sometimes bound to specify types (ie `deepWithKey` only works with arrays`) but it's not easy to guess that without the API doc (maybe that's fine?)
**TODO**:
Fixes: #128
Fixes: #231
> std: Introduce a mergeFull function

- std/merge.js
- std/merge.test.js
I used the wrong type by mistake and ended up with an internal stacktrace. With
this we make sure to throw a human readable error when the user provides the
erroenous input types.
Fixes: #246
> merge: Assert on the merging strategy input types

- Makefile
Before: 35458440 bytes
After: 22379656 bytes
> build: Strip binary to decrease its size

- examples/docker/template-literal-simple/dockerfile.js
- examples/docker/template-literal/dockerfile.js
- examples/jk/handlebars/handlebars.js
- examples/kubernetes/micro-service/micro-service.js
- examples/quick-start/alice/alice.js
- examples/quick-start/terraform-github/github.js
path is the new file. Make sure to have our own examples follow that.
Fixes: #252
> examples: Use path instead of file in generate arrays

- go.mod
The 1.13 toolchain keeps adding that to go.mod. Compiling with 1.12 still works
though. Let's just comply with what the 1.13 toolchain wants to do.
> build: Add version 1.13 to go.mod

- std/internal/data.ts
- std/internal/deferred.ts
- std/internal/rpc.ts
To remove an annoying warning from the build, but also because types are good, this PR ports deferred.js to TypeScript.
In doing so, some ambiguity over how the data from runtime calls is handled gets cleared up. Prior to this, `read` and `internal/rpc` used types that were a bit fishy, but because they went via the untyped `deferred` module, TypeScript could not complain. This commit pins those types down: the post-processing transform _always_ goes from a Uint8Array -- i.e., the bytes -- to `any` (there's no need for them to compose, any more).
> Port deferred.js to TypeScript

- pkg/std/fs.go
- tests/fs-empty-dir-files/index.js
- tests/test-fs-empty-dir.js.cmd
In the return value of `@jkcfg/std/fs#dir`, it's reasonable to assume that even if a directory is empty, you will get an iterable collection of files to loop over. Previously, though, the value was initialised to `nil`, which became `null` in JSON.
> Avoid failures due to null (rather than empty) file listings

- params_option.go
- tests/test-params-parsing.js
- tests/test-params-parsing.js.cmd
- tests/test-params-parsing.js.expected
This lets parameter values be any string (possibly requiring quoting).
> Allow '=' in parameter values

- examples/jk/lodash/lodash.js
- go.mod
- go.sum
- std/index.ts
- std/log.ts
- std/v8worker.d.ts
- std/write.ts
- tests/print-and-log.js
- tests/test-debug-rpc.js
- tests/test-debug-rpcsync.js
- tests/test-fs-walk-preorder.js
- tests/test-jsonstream.js
- tests/test-log.js
- tests/test-log.js.expected
- tests/test-module-resource.js
- tests/test-params-from-file.js
- tests/test-params-from-yaml.js
- tests/test-params-issue-122.js
- tests/test-params-override.js
- tests/test-params.js
- tests/test-parse.js
- tests/test-print.js
- tests/test-print.js.expected
- tests/test-run-dependencies.js
- tests/test-stdin.js
- tests/test-yamlstream.js
- tests/validate-schema.js
- vm.go
Aims:
- output runtime errors, traces, and so on to stderr so they can be treated separate from "deliberate" output
- give JavaScript authors the ability to do the same in libraries and scripts
- Fix #280
This PR:
- Makes sure runtime stuff is output to stderr (in part by updating the V8Worker2 dependency)
- Makes `std.log` output to stderr, by using (the new method) `V8Worker2.log`
- Adds `std.print` which fills much the same purpose as `std.log` did -- it's a casual way to output values
Aside from outputting to stderr, `std.log` behaves a bit differently, since it doesn't go through `write`. There's no formatting options -- strings get printed as-is, and anything else goes through `JSON.stringify` (which by default, keeps everything on one line). This is better suited to logging output, …
> Distinguish between logging to stderr and ad-hoc printing to stdout

- std/fs.ts
Removes a warning from eslint over an unused var, that is provoked by having a function that ignores its argument (which was declared for the sake of showing that it will normally be given an argument ..)
> Avoid unused var warning in fs.ts

- std/generate.ts
- std/transform.ts
Since these are in effect public modules, they ought to have
TypeScript definitions, and the simplest (ha) way to do that is to
rewrite them in TypeScript.
> Port generate.js and transform.js to TypeScript

- Makefile
- generate.go
- std/cmd/generate-module.js
- std/cmd/generate.ts
- std/cmd/transform-exec.js
- std/cmd/transform-module.js
- std/cmd/transform.ts
- std/tsconfig.json
- transform.go
- vm.go
- move std/{generate,transform}.ts to std/cmd/, so they aren't
included in e.g., docs;
- move std/internal/{transform,generate}-module.js "entry point"
templates to std/cmd, so they are with their companions;
- give a @jkcfg/std path when loading the entry points, so they can
import non-public modules
- tell typedoc to ignore cmd/, similarly to internal/
> Move cmd modules

- std/cmd/validate-exec.js
- std/cmd/validate-module.js
- std/cmd/validate.ts
- tests/test-validate-exec.js.cmd
- tests/test-validate-exec.js.expected
- tests/test-validate-module.js.cmd
- tests/test-validate-module.js.expected
- tests/validate-files/invalid.yaml
- tests/validate-files/module.js
- tests/validate-files/valid.yaml
- validate.go
```
$ jk help validate
Validate configuration files
Usage:
jk validate <file>... [flags]
Examples:
validating YAML files using a module's default export
jk validate -m '@example.com/validate' *.{yaml,yml}
validating YAMLs and JSONs using a local script's default export
jk validate ./valid.js *.{yaml,yml,json}
validating a specific file with an inline validation function
jk validate -c 'v => v.name === "correctName"' config.json
Flags:
-d, --emit-dependencies         emit script dependencies
-c, --exec                      treat first argument as specifying literal JavaScript to execute
-h, --help                      help for validate
-m, --module                    treat first argument as specifying a module to load
-o, --output-directory string   where to output generated files
-p, …
```
> Validate command

- std/cmd/validate.ts
- tests/test-validate-promise.js.cmd
- tests/test-validate-promise.js.expected
Validation functions can and often will return a promise of a
result. The template script needs to be able to cope with that.
> Deal with promises returned from validation

- generate.go
- pkg/std/std.go
- run.go
- transform.go
- validate.go
- vm.go
I'd like to add state to the stdlib that persists between std.Execute() calls.
I could add global variables in pkg/std or introduce an object to carry that
state between Execute calls. Went for the latter.
This bit of refactoring will be very useful soon: I need to store
plugin-related state because I want plugins, which are somewhat expensive to
start as they are sub-processes, to be around for the duration of the Std
object.
> std: Introduce an Std object to carry the stdlib context

- examples/quick-start/terraform-github/github.js
- examples/quick-start/terraform-github/test.expected
This references the bigger issue #312 and only makes it work with 0.11 terraform. I think we need to fix the upstream lib to get it to work with 0.12 considering they are dropping support for 0.11 I think it makes sense for this library to only support 0.12 going forward. 
References #312
> Fix terraform example to at least work with 0.11 terraform 

- README.md
Comment on how we handle breaking changes, rather than giving a cover-all disclaimer. Fixes #314.
> De-escalate alpha warning

- std/cmd/validate.ts
- std/schema.ts
- std/validation.test.js
- std/validation.ts
- tests/test-validate-exec.js.expected
- tests/test-validate-module.js.expected
- tests/test-validate-promise.js.expected
This makes `jk validate` handle the structured results from schema validation, as well as the other things we might expect random validation functions to return. Fixes #296
> Cope with structured validation results, e.g., from schema validation

- .travis.yml
- Makefile
- build/Dockerfile
- go.mod
- go.sum
- pkg/std/std.go
- run-in-docker.sh
Just to keep these modern.
There's one change to actual code needed: flatbuffers now returns a `bool` from getters for boolean fields, rather than a byte.
~NB: this needs an update to the prebuilt image, for the MacOSX build to succeed.~ EDIT: I've updated the prebuilt images. Now it complains that the MacOS version is too new -- https://travis-ci.org/jkcfg/jk/jobs/650639395#L169. I'm not sure what it's linking there; the only thing that got replaced is the `flatc` binary. TravisCI doesn't have an image for XCode from 10.15 :-/
> Bump go to 1.13.8 (and flatbuffers to 1.11.0)

- .travis.yml
- run-in-docker.sh
This commit adds directives to the TravicCI config so that it will
cache npm packages (kept in $HOME/.npm when using `npm ci`).
The directory so cached is mounted into the build container, so that
if the host has cached .npm packages, so will the container.
> Ask TravisCI to cache the npm modules

- run-release.sh
In recent changes #320, I migrated the build image to `jkcfg/build` from `quay.io/justkidding/build`. This follows that change through to the image used in the release script, which I missed at the time.
> Switch release script to jkcfg/build

- pkg/std/fs.go
This avoids running out of file handles.
> Close dirs after opening for readdir

- std/write.ts
Most analogues to jk's print() would output a blank line given no
arguments, and without a principled reason to do something else, let's
follow expectations.
> Make print() print a blank line

- std/fs.ts
- tests/test-fs-walk-post.js
- tests/test-fs-walk-post.js.expected
- tests/test-fs-walk-preorder.js
There were a couple of problems with the implementation:
- the pre hook was called before yielding a directory. This isn't
wrong so much as inconvenient -- you can't indent on pre-, and
outdent on post-, for example.
- the post hook was called at the top of the stack, i.e., when
leaving the starting point, so everything had some variety of
off-by-one problem.
This commits makes the tests a bit more rigorous (the post-hook test
in particular didn't check that the number of times leaving a
directory was equal to the number of times entering a
directory!). I've also given the walk procedure some typedocs, so it
has a better explanation in the API reference.
> Take more care with fs#walk

- run.go
It's not only useful to be able to print values, but also to print
them in a particular format; likewise, reading in a particular
encoding.
This addresses #191, though not as requested there :-)
> Make print, Format, Encoding available to -c

- go.mod
- std/cmd/generate.ts
- std/cmd/transform.ts
- std/cmd/validate.ts
- std/read.ts
- tests/test-transform-multidoc-file.expected/test-transform-files/numbers.yaml
- tests/test-transform-multidoc-file.js.cmd
- tests/test-validate-multifile.js.cmd
- tests/test-validate-multifile.js.expected
- tests/testfiles/validate/validate-multi.yaml
Fixes #332 (transform should write a multidoc input to multidoc file) and #333 (validate needs to treat all files that could contain multiple values as having multiple values, and validate all of those values).
> Validate and transform multi-values

- std/resource.d.ts
- std/tsconfig.json
This helps with writing TypeScript with jk, and it also means we can
get some typedoc happening for the resource module.
_En passant_, I've set typedoc to ignore debug.js, which is for
debugging RPC, and v8worker.d.ts, which are internal and don't need
inclusion in the docs.
Fixes #263.
> Provide TypeScript definitions for std/resource

- std/cmd/generate.ts
- std/index.ts
- std/read.ts
- std/write.ts
- tests/test-jsonstream.js
- tests/test-params-issue-122.js
- tests/test-std-ts/test.ts
- tests/test-stdin.js
Up to now, passing `''` has meant stdin (for read) and stdout (for
write), but this is not very guessable.
Instead, use a symbol for each of `stdin` and `stdout`. The
combo-keyword `unique symbol` in TypeScript means that `typeof stdin`
will accept only that symbol (in contrast with the type `symbol`).
This, along with changes to the docs in the website, should help with #161.
> Use const symbols for stdin and stdout

- pkg/resolve/magic_importer.go
- pkg/resolve/magic_importer_test.go
- pkg/resolve/std_importer.go
- pkg/std/fs.go
- pkg/std/read.go
- pkg/std/readbase.go
- pkg/std/std.go
- pkg/vfs/vfs.go
- std/cmd/transform.ts
- std/cmd/validate.ts
- std/internal/host.d.ts
- std/tsconfig.json
- vm.go
Usually jk would forbid reading outside the input directory, but in the case of `jk transform` and `jk validate`, the files to process are given on the command line. It is a standing oddity that these commands invite arbitrary file paths, but can't actually process those outside the current directory.
This PR does a bit of rearranging, and uses the magic module facility, so that the `transform` and `validate` commands are able to read files from the real filesystem, even those with parent paths or absolute paths. This is the mechanism:
- a magic module `@jkcfg/std/internal/host` is created when the VM is initialised, which is registered as having access to the whole filesystem (and not proscribing absolute or parent paths);
- this module can only be imported from `@jkcfg/std/*`;
- …
> Make files mentioned on the command line readable, even with parent paths

- docs/rfc/0000-import-from-images.md
This RFC describes an initial step into using container images as packages, which comes in three parts:
- a system for downloading and caching images locally;
- code to treat a sequence of image layers as a overlay filesystem (including dealing with whiteout files)
- a flag for introducing images to the module search list
> RFC: Using images for packaging

- tests/testfiles/rebase.go
go vet doesn't like `%w` (wrap error) in format strings for fatal errors. This seems picky, but that's its job.
> Avoid %w in fatal errors
